In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import time
import pandas as pd
import re
import datetime
from selenium import webdriver
import pandas as pd
import sys
import pymysql

In [2]:
dt = datetime.datetime.now()
dt = dt.strftime("%Y-%m-%d")
lst= []
tmp = []
driver = webdriver.Chrome(executable_path='./chromedriver')# 크롬웹드라이버 실행코드
driver.implicitly_wait(10)
driver.get('https://finance.naver.com/sise/sise_market_sum.nhn?sosok=0&page=1')
driver.find_element_by_xpath("""//*[@id="option1"]""").click()
driver.find_element_by_xpath("""//*[@id="option24"]""").click()
driver.find_element_by_xpath("""//*[@id="contentarea_left"]/div[2]/form/div/div/div/a[1]/img""").click()
for sosok in range(2): 
    url = 'https://finance.naver.com/sise/sise_market_sum.nhn?sosok=%s&page=1'%sosok
    html = urlopen(url)
    source = BeautifulSoup(html.read(), "html.parser")
    dayPricePageNavigation = source.find_all("table", align="center")
    dayPriceMaxPageSection = dayPricePageNavigation[0].find_all("td", class_="pgRR")
    dayPriceMaxPageNum = int(dayPriceMaxPageSection[0].a.get('href')[-2:])
    
    for k in range(1,dayPriceMaxPageNum+1):                           
        driver.get('https://finance.naver.com/sise/sise_market_sum.nhn?sosok=%s&page=%s'%(sosok,k))#주소불러와서 크롤링 시작
        time.sleep(2) 
        for i in range(2,79):
            if i == 7 or i == 8 or i == 9 or i == 15 or i == 16 or i == 17 or i == 23 or i == 24 or i == 25 or i == 31 or i == 32 or i == 33 or i == 39 or i == 40 or i == 41 or i == 47 or i == 48 or i == 49 or i == 55 or i == 56 or i == 57 or i == 63 or i == 64 or i == 65 or i==71 or i==72 or i==73:
                pass                     
            else:
                if sosok == 0:
                    num = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[1]"""%i).text
                    name = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[2]/a"""%i).text                                   
                    cur  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[3]"""%i).text.replace(',','')
                    diff = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[4]/span"""%i).text.replace(',','')
                    fluck= driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[5]/span"""%i).text
                    face  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[6]"""%i).text.replace(',','')
                    stocks_listed  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[7]"""%i).text.replace(',','')
                    market_cap  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[8]"""%i).text.replace(',','')
                    foriegn  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[9]"""%i).text.replace(',','')
                    per  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[10]"""%i).text.replace(',','').replace('N/A','')
                    roe  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[11]"""%i).text.replace(',','').replace('N/A','')
                    pbr  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[12]"""%i).text.replace(',','').replace('N/A','')
                    tmp = [dt, name,cur,diff,fluck,face,stocks_listed,market_cap,foriegn,per,roe,pbr]
                    lst.append(tmp)
                    if num == '1480':
                        break
                else: 
                    num = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[1]"""%i).text
                    name = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[2]/a"""%i).text                                   
                    cur  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[3]"""%i).text.replace(',','')
                    diff = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[4]/span"""%i).text.replace(',','')
                    fluck= driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[5]/span"""%i).text
                    face  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[6]"""%i).text.replace(',','')
                    stocks_listed  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[7]"""%i).text.replace(',','')
                    market_cap  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[8]"""%i).text.replace(',','')
                    foriegn  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[9]"""%i).text.replace(',','')
                    per  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[10]"""%i).text.replace(',','').replace('N/A','')
                    roe  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[11]"""%i).text.replace(',','').replace('N/A','')
                    pbr  = driver.find_element_by_xpath("""//*[@id="contentarea"]/div[3]/table[1]/tbody/tr[%s]/td[12]"""%i).text.replace(',','').replace('N/A','')
                    tmp = [dt, name,cur,diff,fluck,face,stocks_listed,market_cap,foriegn,per,roe,pbr]
                    lst.append(tmp)
                    if num == '1276':
                        break
df = pd.DataFrame(lst,columns=["날짜","종목명","현재가","전일비","등락률","액면가","상장주식수","시가총액","외국인비율","PER","ROE","PBR"])

In [3]:
df.to_excel("./DATA/crawling_data.xlsx",index=False)
sector = pd.read_excel("./DATA/Sector.xlsx")

df =df.merge(sector,on="종목명",how='left')
#df_a.merge(df_b, on='mukey', how='left')
df["PER"] = df["PER"].fillna(sys.maxsize)
df["PBR"] = df["PBR"].fillna(sys.maxsize)
df["ROE"] = df["ROE"].fillna(-sys.maxsize)
df["Returns"]= df["Returns"].fillna(-sys.maxsize+1)
df.to_excel("./DATA/merge.xlsx",index=False)

In [4]:
df

,날짜,종목명,현재가,전일비,등락률,액면가,상장주식수,시가총액,외국인비율,PER,ROE,PBR,Symbol,Sector,Returns
0,2018-08-05,삼성전자,45750,200,+0.44%,100,6419325,2936841,52.48,8.44,21.01,1.50,5930.0,제조업,-9.223372e+18
1,2018-08-05,SK하이닉스,83300,100,+0.12%,5000,728002,606426,51.03,5.70,36.80,1.74,660.0,제조업,3.015625e+01
2,2018-08-05,셀트리온,280500,1000,-0.36%,1000,125396,351736,22.36,87.79,17.84,14.41,68270.0,제조업,1.733918e+02
3,2018-08-05,삼성전자우,37900,100,+0.26%,100,903629,342475,84.19,6.99,,1.25,NaN,NaN,-9.223372e+18
4,2018-08-05,POSCO,322000,500,-0.16%,5000,87187,280742,57.52,10.06,6.48,0.59,5490.0,제조업,-3.592814e+00
5,2018-08-05,LG화학,391000,16000,+4.27%,5000,70592,276016,37.77,15.73,12.92,1.85,51910.0,제조업,1.416058e+01
6,2018-08-05,현대차,124000,1500,-1.20%,5000,220276,273143,44.45,8.78,5.92,0.48,5380.0,제조업,-1.621622e+01
7,2018-08-05,삼성바이오로직스,392000,14000,+3.70%,2500,66165,259367,9.68,-267.39,-2.41,6.52,207940.0,제조업,4.100719e+01
8,2018-08-05,NAVER,731000,3000,+0.41%,500,32963,240957,60.28,31.18,18.50,4.51,35420.0,서비스업,-8.165829e+00
9,2018-08-05,삼성물산,122000,1000,+0.83%,100,189690,231422,11.44,36.48,3.13,0.89,28260.0,도매업,-1.285714e+01
10,2018-08-05,KB금융,52800,300,+0.57%,5000,418112,220763,69.34,6.67,10.18,0.62,105560.0,금융업,-1.050847e+01
11,2018-08-05,현대모비스,224500,1000,+0.45%,5000,97344,218537,48.66,13.94,5.43,0.73,12330.0,제조업,-1.143984e+01
12,2018-08-05,SK텔레콤,257000,4000,+1.58%,500,80746,207516,41.79,7.98,15.38,1.02,17670.0,통신업,-7.052441e+00
13,2018-08-05,한국전력,31850,50,+0.16%,5000,641964,204466,28.58,15.74,1.81,0.29,15760.0,전기업,-2.834646e+01
14,2018-08-05,신한지주,43050,500,+1.18%,5000,474200,204143,69.37,7.00,9.13,0.62,55550.0,금융업,-2.086397e+01
15,2018-08-05,LG생활건강,1272000,19000,+1.52%,5000,15618,198663,46.40,37.15,21.94,7.11,51900.0,제조업,3.113402e+01
16,2018-08-05,삼성생명,95200,300,-0.31%,500,200000,190400,16.07,16.33,4.51,0.58,32830.0,금융업,-2.260163e+01
17,2018-08-05,SK,256500,1500,-0.58%,200,70360,180474,25.31,10.85,12.53,1.06,34730.0,금융업,-6.727273e+00
18,2018-08-05,SK이노베이션,189000,2000,-1.05%,5000,92466,174760,40.24,8.42,11.96,0.97,96770.0,금융업,5.000000e+00
19,2018-08-05,삼성에스디에스,209000,1000,-0.48%,500,77378,161720,11.94,30.49,9.91,2.91,18260.0,관리업,1.708683e+01
20,2018-08-05,아모레퍼시픽,275500,5500,+2.04%,500,58458,161053,34.61,48.26,9.81,4.57,90430.0,제조업,-1.431127e+00
21,2018-08-05,삼성SDI,231000,4500,+1.99%,5000,68765,158846,38.42,24.74,5.98,1.37,6400.0,제조업,2.762431e+01
22,2018-08-05,KT&G,104000,0,0.00%,5000,137292,142784,54.00,12.27,15.71,1.69,33780.0,제조업,-8.370044e+00
23,2018-08-05,하나금융지주,43900,0,0.00%,5000,300242,131806,71.42,6.38,8.79,0.54,86790.0,금융업,-1.341223e+01
24,2018-08-05,S-Oil,115500,1500,+1.32%,2500,112583,130033,76.72,10.80,18.84,1.97,10950.0,제조업,-2.118644e+00
25,2018-08-05,LG,74600,600,+0.81%,5000,172557,128728,34.11,5.48,16.04,0.82,3550.0,금융업,-1.971091e+00
26,2018-08-05,삼성화재,265500,1500,-0.56%,500,47375,125780,50.64,13.89,8.46,0.95,810.0,금융업,-1.135225e+01
27,2018-08-05,기아차,31000,50,-0.16%,5000,405363,125663,39.47,12.98,3.62,0.46,270.0,제조업,-1.632928e+01
28,2018-08-05,LG전자,75200,100,+0.13%,5000,163648,123063,33.92,7.88,13.69,1.02,66570.0,제조업,5.027933e+00
29,2018-08-05,넷마블,143000,500,+0.35%,100,85210,121851,26.24,36.69,11.17,2.81,251270.0,공급업,9.578544e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2726,2018-08-05,신한제4호스팩,2055,10,-0.48%,100,6010,124,0.00,,,,277480.0,서비스업,3.007519e+00
2727,2018-08-05,대신밸런스제3호스팩,2075,20,+0.97%,100,5510,114,0.16,,,,253590.0,서비스업,3.491272e+00
2728,2018-08-05,한국4호스팩,2045,0,0.00%,100,5500,112,0.00,,0.50,,240540.0,서비스업,-9.685230e-01
2729,2018-08-05,하나금융11호스팩,2040,0,0.00%,100,5401,110,0.02,,,,284620.0,서비스업,1.745636e+00
2730,2018-08-05,케이비제10호스팩,2060,0,0.00%,100,5210,107,0.04,,0.30,,250930.0,서비스업,2.743142e+00
2731,2018-08-05,대신밸런스제4호스팩,2090,40,+1.95%,100,5010,105,0.00,,,,262830.0,서비스업,4.761905e+00
2732,2018-08-05,한국제7호스팩,2045,0,0.00%,100,5060,103,0.00,,,,291210.0,서비스업,2.763819e+00
2733,2018-08-05,하이에이아이1호스팩,2075,0,0.00%,100,4950,103,0.24,,0.62,,235010.0,서비스업,3.491272e+00
2734,2018-08-05,미래에셋대우스팩1호,2065,15,-0.72%,100,4840,100,0.00,,,,265480.0,서비스업,2.736318e+00
2735,2018-08-05,미래에셋제5호스팩,2080,0,0.00%,100,4800,100,0.00,,0.61,,239340.0,서비스업,1.463415e+00
2736,2018-08-05,동부스팩5호,2030,10,-0.49%,100,4840,98,0.00,,,,281740.0,서비스업,3.307888e+00
2737,2018-08-05,에임하이,150,42,-21.87%,500,65263,98,60.03,-0.26,-29.91,0.07,43580.0,제조업,-9.613900e+01
2738,2018-08-05,IBKS제5호스팩,2155,35,-1.60%,100,4500,97,0.00,,0.58,,254120.0,서비스업,4.106280e+00
2739,2018-08-05,하나금융10호스팩,2045,15,-0.73%,100,4602,94,0.00,,,,270520.0,서비스업,1.995012e+00
2740,2018-08-05,IBKS제6호스팩,2180,0,0.00%,100,4315,94,0.00,,,,264850.0,서비스업,8.728180e+00
2741,2018-08-05,한국제6호스팩,2080,5,+0.24%,100,4510,94,0.00,,,,281410.0,서비스업,5.583756e+00
2742,2018-08-05,한화수성스팩,2070,0,0.00%,100,4440,92,0.00,,,,265920.0,서비스업,3.759398e+00
2743,2018-08-05,하나금융9호스팩,2040,10,-0.49%,100,4260,87,0.00,,,,261200.0,서비스업,-4.878049e-01
2744,2018-08-05,유안타제3호스팩,2040,0,0.00%,100,4235,86,0.00,,,,287410.0,서비스업,3.030303e+00
2745,2018-08-05,IBKS제7호스팩,2300,0,0.00%,100,3650,84,0.00,,,,276920.0,서비스업,1.358025e+01
2746,2018-08-05,교보7호스팩,2065,10,-0.48%,100,4020,83,0.00,,,,267320.0,서비스업,2.227723e+00
2747,2018-08-05,한국제5호스팩,2040,0,0.00%,100,4000,82,0.00,,,,271740.0,서비스업,2.000000e+00
2748,2018-08-05,SK3호스팩,2065,25,-1.20%,100,3600,74,0.00,,0.40,,232330.0,서비스업,2.736318e+00
2749,2018-08-05,신한제3호스팩,2115,10,-0.47%,100,3505,74,0.00,,0.65,,257730.0,서비스업,1.438849e+00
2750,2018-08-05,한화에이스스팩4호,2055,0,0.00%,100,3495,72,0.00,,,,279410.0,서비스업,3.778338e+00
2751,2018-08-05,IBKS제8호스팩,3200,75,+2.40%,100,2210,71,0.10,,,,277410.0,서비스업,5.058824e+01
2752,2018-08-05,케이비제11호스팩,2095,5,+0.24%,100,3210,67,0.00,,,,258790.0,서비스업,4.228856e+00
2753,2018-08-05,대호피앤씨우,1560,0,0.00%,500,4242,66,0.66,27.37,,1.73,NaN,NaN,-9.223372e+18
2754,2018-08-05,한화에이스스팩3호,2105,5,+0.24%,100,3080,65,0.00,,,,264290.0,서비스업,-9.223372e+18
2755,2018-08-05,IBKS제9호스팩,2305,15,-0.65%,100,2760,64,0.41,,,,NaN,NaN,-9.223372e+18

In [5]:
conn = pymysql.Connect(host='pythondb.ceekfdzgubcw.ap-northeast-2.rds.amazonaws.com',
                       port = 3306,
                       user = 'root',
                       passwd = 'wldnjs0216',
                       database = 'ppp',
                       charset = 'utf8',
                       autocommit=True)
cursor = conn.cursor()
cursor.execute("DROP TABLE IF EXISTS `stockInfo`")
cursor.execute("CREATE TABLE IF NOT EXISTS `stockInfo`(`date` VARCHAR(50) NULL ,`name` VARCHAR(50) NULL ,`price` FLOAT(20) NULL ,`diff` FLOAT(20) NULL  ,`diff_per` VARCHAR(20) NULL  ,`face` FLOAT(20) NULL  ,`stocks_listed` FLOAT(20) NULL  ,`market_cap` FLOAT(20) NULL ,`foriegn` FLOAT(20) NULL  ,`per` FLOAT(20) NULL ,`roe` FLOAT(20) NULL ,`pbr` FLOAT(20) NULL, `Symbol` VARCHAR(10) NULL, `sector` VARCHAR(10) NULL, `returns` FLOAT(20) NULL,PRIMARY KEY(`name`))")
for i in  range(len(df.index)):
    cursor.execute("INSERT INTO `stockInfo` VALUES('%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')"%(df.iloc[i,0],df.iloc[i,1],df.iloc[i,2],df.iloc[i,3],df.iloc[i,4],df.iloc[i,5],df.iloc[i,6],df.iloc[i,7],df.iloc[i,8],df.iloc[i,9],df.iloc[i,10],df.iloc[i,11],df.iloc[i,12],df.iloc[i,13],df.iloc[i,14]))

InternalError: (1366, "Incorrect double value: '' for column 'roe' at row 1")